[package]
name = "qwerty-learner-audio"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
neon = "1.0"
rodio = "0.17"
reqwest = { version = "0.11", features = ["blocking"] }
